# Generated by Django 3.2.7 on 2021-10-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='myphoto')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
